version: '3.8'
services:
  discovery-service:
    build: ./discoveryService
    container_name: discovery-service
    ports:
      - "8761:8761"
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
