apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: anasdevops/reviewservice:latest
          ports:
            - containerPort: 9095
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/review_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
    - port: 9095
      targetPort: 9095
